### ISSUE TITLE
DFHack init file locations are changing

### ISSUE THREAD

**Issue by myk002** [Pidgeot/python-lnp#181]
I wanted to give you a heads up that in order to support DFHack's work on usability and in-game configuration, the dfhack init files (`dfhack*.init`, `onLoad*.init`, `onMapLoad*.init`, and the others) will be moving from the DF root directory to `dfhack-config/init/`.

the `dfhack.history` file (along with all other history files) will also be moving to `dfhack-config/`

For the LNP, I think this means the following changes:
- core/hacks.py will need to be updated with the new init file directory
- the reference to `<df>/dfhack.history` in `PyLNP.json` will need to change to `<df>/dfhack-config/dfhack.history`

A new build of DFHack that you can use to test with is available from https://buildmaster.lubar.me/api/ci-badges/link?page=build&key=badges&$ApplicationId=3&$BinariesAvailable=true

**Comment by myk002** [comment]
I linked to this issue from all the pack maintainers' threads:
Windows (PeridexisErrant): http://www.bay12forums.com/smf/index.php?topic=126076.msg8407015#msg8407015
Linux (McArcady): http://www.bay12forums.com/smf/index.php?topic=157712.msg8407023#msg8407023
Mac (jecowa): http://www.bay12forums.com/smf/index.php?topic=158322.msg8407041#msg8407041

Which changes need to be made in LNP and which should be made by the pack maintainers?

**Comment by Pidgeot** [comment]
What you mentioned would be done here, but it's up to the pack maintainers to bring in the new versions, of course. If they customize PyLNP.json, they have to make sure to carry their things over.

Rather than explicitly reference dfhack-config in those places, though, I think it'd be better to detect whether we need to use the dfhack-config folder - people might be playing older versions and I don't want to break compatibility if it's avoidable. This is easily done, since there's a path labeling system already;  I just need to know how I'd know.

Is there some file or folder I can rely on the existence of in builds that will use that folder for these files? I'm afraid I don't use DFHack myself, so I'm not too sure of what a normal folder would look like...

**Comment by myk002** [comment]
if `dfhack-config/init` exists, then they're using (or at least they have used sometime in the past) a new version of DFHack that reads from that directory. It didn't exist until now.

**Comment by myk002** [comment]
actually, scratch that. `dfhack-config/init` won't exist until DF has been run at least once with the new DFHack installed. LNP may need to know which file to edit *before* DF is run for the first time. You should check for `hack/init`, which only exists in new DFHack versions and will exist even before DF is run for the first time.

**Comment by Pidgeot** [comment]
That doesn't exist in the build you linked me to, though. I'd need something that works before it's ever been run.

**Comment by Pidgeot** [comment]
That works for me. I will try to get to it this weekend, but if you want to contribute a pull request before then, feel free.

**Comment by myk002** [comment]
Thanks! This weekend is fine. DFHack still has tasks we need to complete before we can spin a release. I just wanted to give you (and the pack maintainers) a good amount of lead time.

**Comment by Pidgeot** [comment]
For the record, this isn't in a build yet, but that should happen within a day or two.

**Comment by myk002** [comment]
Thank you very much! I'll work with the pack maintainers to update (if they haven't already).
