### ISSUE TITLE
iOS version for jailbroken devices?

### ISSUE THREAD

**Issue by tonn333** [Pidgeot/python-lnp#193]
I have a terminal and python 3.9 on my iPad pro 12.9
Was wondering if it would be possible to make it work on my device?
Could I get some help making it happen?

**Comment by Pidgeot** [comment]
Unfortunately, I don't have access to any iOS devices, jailbroken or otherwise. Even if you got it running, I'm pretty sure Dwarf Fortress itself doesn't run on iOS, so I'm not sure what you'd want it to do.

If you want to experiment, feel free, and if you have concrete questions, I can at least try to answer them - but if it's too iOS-specific, it's quite unlikely I'll know.

**Comment by Pidgeot** [comment]
DF itself doesn't use Python, only this launcher does. As far as I know, the current Mac builds of Dwarf Fortress only support Intel CPUs, not ARM, and I don't believe iOS includes the emulation layer needed to run these binaries.

Maybe that'll change in the future, but until then, it's not clear that there's much point in getting PyLNP working.

**Comment by tonn333** [comment]
Thank you for the explanation. 

Meanwhile I found this:
https://www.reddit.com/r/dwarffortress/comments/kstzzv/tutorial_dwarf_fortress_running_directly_on_arm/

So running it on much more powerful ipad should be possible. 

Do you know if there is an arm version coming? Now that mac went arm.

**Comment by Pidgeot** [comment]
I'm not involved with Dwarf Fortress development, so I have no clue. Only Toady knows what he might be planning.

**Comment by tonn333** [comment]
Thank you!
